### ISSUE TITLE
Extract more information from the `config.yaml`  file with `DeepLabCutInterface` 

### ISSUE THREAD

**Issue by h-mayorquin** [catalystneuro/neuroconv#1030]
Currently, we are only extracting the task as a session description and experimenter:

https://github.com/catalystneuro/neuroconv/blob/727228c8bd871d0ffdcca48ac76a2010f293652d/src/neuroconv/datainterfaces/behavior/deeplabcut/deeplabcutdatainterface.py#L55-L66

We will make this optional.

We are on a crunch now for a project but in a future project that uses DeepLabCut's  `config.yaml` we should figure out what more metadata could be extracted from those configuration files. From the test data it seems that at least the names of the body parts could be incluced as metadata somewhere.

This is the `config.yaml` file contents from the test data that we have on gin:

```yaml
    # Project definitions (do not edit)
Task: openfield
scorer: Pranav
date: Aug20
multianimalproject: false
identity:

    # Project path (change when moving around)
project_path: /Users/sakshamsharda/Documents/NWB/GIN/behavior_testing_data/DLC

    # Annotation data set configuration (and individual video cropping parameters)
video_sets:
  /Data/openfield-Pranav-2018-08-20/videos/m1s1.mp4:
    crop: 0, 640, 0, 480
  /Data/openfield-Pranav-2018-08-20/videos/m1s2.mp4:
    crop: 0, 640, 0, 480
  /Data/openfield-Pranav-2018-08-20/videos/m2s1.mp4:
    crop: 0, 640, 0, 480
  /Data/openfield-Pranav-2018-08-20/videos/m3s1.mp4:
    crop: 0, 640, 0, 480
  /Data/openfield-Pranav-2018-08-20/videos/m3s2.mp4:
    crop: 0, 640, 0, 480
  /Data/openfield-Pranav-2018-08-20/videos/m4s1.mp4:
    crop: 0, 640, 0, 480
  /Data/openfield-Pranav-2018-08-20/videos/m5s1.mp4:
    crop: 0, 800, 0, 800
  /Data/openfield-Pranav-2018-08-20/videos/m6s1.mp4:
    crop: 0, 800, 0, 800
  /Data/openfield-Pranav-2018-08-20/videos/m6s2.mp4:
    crop: 0, 800, 0, 800
  /Data/openfield-Pranav-2018-08-20/videos/m7s1.mp4:
    crop: 0, 800, 0, 800
  /Data/openfield-Pranav-2018-08-20/videos/m7s2.mp4:
    crop: 0, 800, 0, 800
  /Data/openfield-Pranav-2018-08-20/videos/m7s3.mp4:
    crop: 0, 800, 0, 800
  /Data/openfield-Pranav-2018-08-20/videos/m8s1.mp4:
    crop: 0, 800, 0, 800

bodyparts:
- snout
- leftear
- rightear
- tailbase

start: 0
stop: 1
numframes2pick: 20

    # Plotting configuration
skeleton: []
skeleton_color: black
pcutoff: 0.4
dotsize: 8
alphavalue: 0.7
colormap: jet

    # Training,Evaluation and Analysis configuration
TrainingFraction:
- 0.95
iteration: 1
default_net_type: resnet_50
default_augmenter: default
snapshotindex: -1
batch_size: 1

    # Cropping Parameters (for analysis and outlier frame detection)
cropping: false
    #if cropping is true for analysis, then set the values here:
x1: 0
x2: 640
y1: 277
y2: 624

    # Refinement configuration (parameters from annotation dataset configuration also relevant in this stage)
corner2move2:
- 50
- 50
move2corner: true
croppedtraining:

```
